---

# Playbook to test the persistent memory
- import_playbook: deploy-ghost.yml

- name: Tests
  hosts: localhost
  gather_facts: true
  roles:
    - { role: test_pvc }

- import_playbook: undeploy-ghost.yml delete_data='true'

- import_playbook: deploy-ghost.yml

- name: Test delete pv
  hosts: localhost
  gather_facts: true
  roles:
    - { role: test_delete_pvc }

