---
- name: Create Ghost deployment file
  template:
    src: ghost-deployment
    dest: "{{ k8s_files_path }}/ghost-deployment.yml"

- name: Create Ghost service file
  template:
    src: ghost-service
    dest: "{{ k8s_files_path }}/ghost-service.yml"

- name: Deploy Ghost
  k8s:
    state: present
    src: "{{ k8s_files_path }}/ghost-deployment.yml"
    wait: yes

- name: Deploy Ghost Service
  k8s:
    state: present
    src: "{{ k8s_files_path }}/ghost-service.yml"
    wait: yes

