---
## TODO: Add Ansible configuration here
## FIXME: Needs to be tested!!!
- name: Install pre-requisites
  pip:
    name:
      - kubernetes

- name: Create namespace
  k8s:
    name: ghost
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Ghost
  k8s:
    state: present
    src: ghost/ghost-deployment.yml

- name: Deploy Ghost Service
  k8s:
    state: present
    src: ghost/ghost-service.yml

- name: Set Namespace Preference
  shell: kubectl config set-context --current --namespace={{ k8s_namespace }}
