---
- name: Create MySQL deployment file
  template:
    src: mysql-deployment
    dest: "{{ k8s_files_path }}/mysql-deployment.yml"

- name: Create MySQL pvc file
  template:
    src: mysql-pvc
    dest: "{{ k8s_files_path }}/mysql-pvc.yml"

- name: Create MySQL service file
  template:
    src: mysql-service
    dest: "{{ k8s_files_path }}/mysql-service.yml"

- name: Deploy MySQL
  k8s:
    state: present
    src: "{{ k8s_files_path }}/mysql-deployment.yml"

- name: Add MySQL Persistent Volume Claim
  k8s:
    state: present
    src: "{{ k8s_files_path }}/mysql-pvc.yml"

- name: Deploy MySQL Service
  k8s:
    state: present
    src: "{{ k8s_files_path }}/mysql-service.yml"
