---
- name: Create a k8s namespace for MySQL
  k8s:
    name: mysql
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy MySQL
  k8s:
    state: present
    src: mysql/mysql-deployment.yml

- name: Add MySQL Persistent Volume Claim
  k8s:
    state: present
    src: mysql/mysql-pvc.yml

- name: Deploy MySQL Service
  k8s:
    state: present
    src: mysql/mysql-service.yml
