---
- name: Unploying Ghost and MySQL
  shell:
    kubectl delete all --all -n {{ k8s_namespace }}

#- name: Deleting Deployments and services in the namespace
#  k8s:
#    name: "{{ item }}"
#    api_version: v1
#    kind: Namespace
#    state: absent
#    wait: yes
#  loop:
#    - "mysql-deployment"
#    - "mysql-service"
#    - "ghost-deployment"
#    - "ghost-service"

- name: Deleting temporary folder
  file:
    path: "{{ tmp_folder_path }}"
    state: absent

- name: Deleting Persistent Volume Claim
  k8s:
    name: mysql-pv-claim
    api_version: v1
    kind: PersistentVolumeClaim
    state: absent
    wait: yes
  when: delete_data is defined and delete_data == 'true'
