- name: Set constant timer delay
  set_fact:
      constant_timer_delay: 300 # In milliseconds

- name: Set number of threads to 10
  set_fact:
      thread_num: 10

- name: Create jmeter workload file
  template:
    src: workload
    dest: "{{ k8s_files_path }}/workload.jmx"

- name: Run jmeter workload with {{ thread_num }} threads
  shell: "./jmeter/apache-jmeter-5.5/bin/jmeter -n -t {{ k8s_files_path }}/workload.jmx -l {{ k8s_files_path }}/results.jtl"
  register: jmeter_output
  changed_when: false

- name: Change thread number to 100
  set_fact:
      thread_num: 100

- name: Run jmeter workload with {{ thread_num }} threads
  shell: "./jmeter/apache-jmeter-5.5/bin/jmeter -n -t {{ k8s_files_path }}/workload.jmx -l {{ k8s_files_path }}/results.jtl"
  register: jmeter_output
  changed_when: false

- name: Change thread number to 500
  set_fact:
    thread_num: 500

- name: Run jmeter workload with {{ thread_num }} threads
  shell: "./jmeter/apache-jmeter-5.5/bin/jmeter -n -t {{ k8s_files_path }}/workload.jmx -l {{ k8s_files_path }}/results.jtl"
  register: jmeter_output
  changed_when: false
