---
- name: Install pre-requisites
  pip:
    name:
      - kubernetes

- name: Create namespace
  k8s:
    name: ghost
    api_version: v1
    kind: Namespace
    state: present

- name: Create temporary folder
  file:
    path: tmp
    state: directory

- name: Set Namespace Preference
  shell: kubectl config set-context --current --namespace={{ k8s_namespace }}
