---
- name: Install pre-requisites
  pip:
    name:
      - kubernetes
      - bcrypt
      - openshift

- name: Create namespace
  k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: yes

- name: Create temporary folder
  file:
    path: "{{ tmp_folder_path }}"
    state: directory

- name: Set Namespace Preference
  shell: kubectl config set-context --current --namespace={{ k8s_namespace }}

#- name: Download and unpack JMeter
#  unarchive:
#    src: https://downloads.apache.org/jmeter/binaries/apache-jmeter-{{ jmeter_version }}.tgz
#    dest: tmp
#    remote_src: yes
